# Generated by Django 6.0.1 on 2026-02-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0002_supportquery_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_proplus',
            field=models.BooleanField(default=False),
        ),
    ]
