# Generated by Django 6.0.1 on 2026-02-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
