# Generated by Django 6.0.1 on 2026-02-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0005_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(choices=[('Pro', 'Pro'), ('Pro Plus', 'Pro Plus')], default='Pro', max_length=50),
        ),
    ]
