# Generated by Django 6.0.1 on 2026-02-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0006_alter_subscription_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
