# Generated by Django 6.0.1 on 2026-02-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0007_subscription_billing_cycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date']},
        ),
    ]
