# Generated by Django 6.0.1 on 2026-02-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0008_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=2, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
