# Generated by Django 6.0.1 on 2026-02-10 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0010_remove_appointment_reminder_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('BEHAVIORAL', 'Behavioral'), ('TECHNICAL', 'Technical'), ('CASE_STUDY', 'Case Study')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_mock_interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='target_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='waitlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mock_interviews_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MockInterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_report', models.FileField(blank=True, null=True, upload_to='feedback_reports/')),
                ('improvement_plan', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='VCS.appointment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
