# Generated by Django 6.0.1 on 2026-02-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0011_appointment_interview_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('max_slots', models.PositiveIntegerField(default=5)),
                ('used_slots', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
