# Generated by Django 6.0.1 on 2026-02-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0012_interviewslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VCS.jobapplication'),
        ),
    ]
