# Generated by Django 6.0.1 on 2026-02-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0013_alter_appointment_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='max_enrollments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='tier_required',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('PRO_PLUS', 'Pro Plus')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='certificates_earned',
            field=models.ManyToManyField(related_name='earned_by', to='VCS.certificate'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('COMPLETED', 'Completed')], default='ENROLLED', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VCS.course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VCS.profile')),
            ],
            options={
                'unique_together': {('profile', 'course')},
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VCS.enrollment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_users', through='VCS.Enrollment', to='VCS.course'),
        ),
        migrations.CreateModel(
            name='ProgressStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('is_webinar', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VCS.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VCS.enrollment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VCS.progressstep')),
            ],
            options={
                'unique_together': {('enrollment', 'step')},
            },
        ),
    ]
