# Generated by Django 6.0.1 on 2026-02-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0014_certificate_course_has_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='current_stage',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('STARTED', 'Started Course'), ('EXAMS', 'Exams'), ('INTERVIEW', 'Interview'), ('CERTIFIED', 'Certified')], default='ENROLLED', max_length=20),
        ),
    ]
