# Generated by Django 6.0.1 on 2026-02-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0016_badge_appointment_sla_complied_appointment_sla_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='current_stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('STARTED', 'Started Course'), ('EXAMS', 'Exams'), ('INTERVIEW', 'Interview'), ('CERTIFIED', 'Certified')], default='ENROLLED', max_length=20),
        ),
    ]
