# Generated by Django 6.0.1 on 2026-02-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0017_alter_enrollment_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses_enrolled_this_month',
            field=models.IntegerField(default=0),
        ),
    ]
