# Generated by Django 6.0.1 on 2026-02-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0019_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consultant_hours_used_this_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
