# Generated by Django 6.0.1 on 2026-02-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0020_profile_consultant_hours_used_this_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses_enrolled_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
