# Generated by Django 6.0.1 on 2026-02-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0022_badge_icon_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_trainee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='trainee_plan',
            field=models.CharField(choices=[('pro', 'Pro'), ('proplus', 'Pro Plus')], default='pro', max_length=10),
        ),
    ]
