from django.urls import path
from .views import (home,signup,job_list,search,job_detail,save_job,apply_job,
                    profile, saved_jobs, applied_jobs,upgrade_plan,subscription_dashboard,
                    job_matching,ai_resume_optimizer,user_login,
                    courses,admin_job_applications,application_tracker,
                    admin_dashboard,admin_candidates,admin_candidate_detail,
                    schedule_interview,admin_queries,escalate_query,admin_jobs,
                    add_job,edit_job,delete_job,admin_analytics,notifications,mark_notification_read,
                    admin_application_detail,admin_applications_by_status,
                    send_support_query,candidate_chat,send_message,clear_chat,
                    chatbot_api,chat_history,chatfaq_delete,chatfaq_list,chatfaq_save,
                    mark_query_resolved,reply_query,payment_success,calendar_events,
                    appointment_list_api,admin_calendar,consultant_dashboard,
                    appointment_list,create_interview_appointment,create_one_on_one_appointment,
                    edit_appointment,postpone_appointment,update_appointment_status,
                    schedule_mock_interview,upload_mock_feedback,mark_done_with_feedback,
                    appointment_view,view_feedback,user_feedbacks,
                    enroll_course,training_progress,training_dashboard,
                    admin_course_details,admin_user_progress,sync_progress,
                    admin_courses,admin_add_course,admin_consultant_tracking,
                    ratelimit_error,)

urlpatterns = [
    path('', home, name='home'),
    path('login/', user_login, name='login'),
    path('signup/', signup, name='signup'),
    path('search/', search, name='search'),
    path('jobs/', job_list, name='job_list'),
    path('jobs/<int:pk>/', job_detail, name='job_detail'),
    path('jobs/<int:pk>/save/', save_job, name='save_job'),
    path('apply/<int:pk>/', apply_job, name='apply_job'),
    path('profile/', profile, name='profile'),
    path('saved-jobs/', saved_jobs, name='saved_jobs'),
    path('applied-jobs/', applied_jobs, name='applied_jobs'),
    path('upgrade/', upgrade_plan, name='upgrade_plan'),
    path('subscription/', subscription_dashboard, name='subscription'),
    path('job-matching/', job_matching, name='job_matching'),
    path('resume-ai/', ai_resume_optimizer, name='resume_ai'),
    path('courses/', courses, name='courses'),
    path('notifications/', notifications, name='notifications'),
    path("notifications/read/<int:notification_id>/", mark_notification_read, name="mark_notification_read"),
    path('admin/job/<int:job_id>/applications/', admin_job_applications, name='admin_job_applications'),
    path('application/<int:application_id>/',application_tracker,name='application_tracker'),
    path('ratelimit/', ratelimit_error, name='ratelimit_error'),


    path('chat/', candidate_chat, name='candidate_chat'),
    path('chat/send/', send_message, name='send_message'),
    path('chat/clear/', clear_chat, name='clear_chat'),
    path('chatbot/', chatbot_api, name='chatbot_api'),
    path('chat/history/', chat_history, name='chat_history'),

    path('dashboard/chatfaq/', chatfaq_list, name='chatfaq'),
    path('dashboard/chatfaq/save/', chatfaq_save, name='chatfaq_save'),
    path('dashboard/chatfaq/delete/<int:id>/', chatfaq_delete, name='chatfaq_delete'),

    path("payment-success/", payment_success, name="payment_success"),

    path('dashboard/', admin_dashboard, name='admin_dashboard'),
    path('dashboard/candidates/', admin_candidates, name='admin_candidates'),
    path('dashboard/candidate/<int:user_id>/', admin_candidate_detail, name='admin_candidate_detail'),
    path("dashboard/schedule-interview/<int:application_id>/", schedule_interview, name="schedule_interview"),
    path('dashboard/queries/', admin_queries, name='admin_queries'),
    path('dashboard/query/<int:query_id>/escalate/', escalate_query, name='escalate_query'),
    path("send-support-query/", send_support_query, name="send_support_query"),
    path("dashboard/queries/resolve/<int:query_id>/", mark_query_resolved, name="mark_query_resolved"),
    path("dashboard/query/<int:query_id>/reply/", reply_query, name="reply_query"),

    path('dashboard/jobs/', admin_jobs, name='admin_jobs'),
    path('dashboard/jobs/add/', add_job, name='add_job'),
    path('dashboard/jobs/edit/<int:job_id>/', edit_job, name='edit_job'),
    path('dashboard/jobs/delete/<int:job_id>/', delete_job, name='delete_job'),
    path('dashboard/analytics/', admin_analytics, name='admin_analytics'),
    path('dashboard/applications/<int:application_id>/', admin_application_detail, name='admin_application_detail'),
    path('dashboard/applications/status/<str:status>/', admin_applications_by_status, name='admin_applications_by_status'),
    

    path("dashboard/consultant/",consultant_dashboard,name="consultant_dashboard"),
    path("dashboard/appointments/list/", appointment_list_api,name="appointment_list"),
    path("dashboard/calendar/", admin_calendar, name="admin_calendar"),
    path("dashboard/calendar/events/", calendar_events, name="calendar_events"),
    path('user/feedbacks/', user_feedbacks, name='user_feedbacks'),

    path('dashboard/appointments/view/<int:appointment_id>/', appointment_view, name='appointment_view'),
    path('dashboard/appointments/<int:appointment_id>/view-feedback/', view_feedback, name='view_feedback'),
    path('dashboard/appointments/', appointment_list, name='appointment_list'),
    path('dashboard/appointments/create/interview/', create_interview_appointment, name='appointment_create_interview'),
    path('dashboard/appointments/create/one-on-one/', create_one_on_one_appointment, name='appointment_create_one_on_one'),

    path('schedule-mock-interview/', schedule_mock_interview, name='schedule_mock_interview'),
    path('dashboard/appointments/<int:appointment_id>/upload-feedback/', upload_mock_feedback, name='upload_mock_feedback'),
    path('dashboard/appointments/<int:appointment_id>/mark-done/', mark_done_with_feedback, name='mark_done_with_feedback'),
    path('dashboard/appointments/edit/<int:appointment_id>/', edit_appointment, name='appointment_edit'),
    path('dashboard/appointments/postpone/<int:appointment_id>/', postpone_appointment, name='appointment_postpone'),
    path('dashboard/appointments/status/<int:appointment_id>/<str:status>/', update_appointment_status, name='appointment_mark_done'),

    
    path('dashboard/training/courses/add/', admin_add_course, name='admin_add_course'),
    path('enroll/<int:course_id>/', enroll_course, name='enroll_course'),
    path('training/progress/', training_progress, name='training_progress'),
    path('training/dashboard/', training_dashboard, name='training_dashboard'),
    path('dashboard/training/courses/', admin_courses, name='admin_courses'),
    path('dashboard/training/course/<int:course_id>/', admin_course_details, name='admin_course_details'),
    path('dashboard/training/enrollment/<int:enrollment_id>/', admin_user_progress, name='admin_user_progress'),
    path('dashboard/training/sync/', sync_progress, name='sync_progress'),

    path('dashboard/consultant-tracking/',admin_consultant_tracking, name='admin_consultant_tracking'),
]


